### ISSUE TITLE
Visible resistances/vulnerabilities

### ISSUE THREAD

**Issue by anhegofcherek** [prophecymud/ideas#1]
As much as I loved the metagame around dealing with hidden resistances/vulns on eq - the endless testing, rumours, and hidden knowledge etc. - I'm not sure I love the notion of hiding things like that from players. It's definitely not fun to find out you've got an invisible vulnerability.

I think I want to make them visible.

I don't anticipate huge impact on gameplay - many of the common ones are known anyway - but I can see it being a nicer experience for players in terms of reducing unpleasant surprises.

**Comment by grekan** [comment]
I wholeheartedly endorse this. Please implement as soon as possible! 

Also Anheg rules.

**Comment by Ranfir** [comment]
I can't think of any good reason not to do this. Hunting for resistances just isn't something that players have the time or motivation to do anymore. (Then again, the same could be said for PvP, which is why people care about this in the first place.)

Alternatives to making them visible might be:
1. Pay some amount of gold/aqp/qp to make them visible on a single item.
2. Add strong hints around the items such that players would know that the item has some resistance or vulnerability. (As is, it simply doesn't make sense to test every single item in the game.)
3. Make an indication of the presence of hidden attributes instead of making them outright visible.

**Comment by anhegofcherek** [comment]
> Hunting for resistances just isn't something that players have the time or motivation to do anymore

I'm less bothered by that - if you don't have the time, fine

I'm more bothered by the fact that it's "not fun" - I'm aware that fun is subjective, but I think I'm using reasonably general widespread assessments here:

* It can be fun to trade on the rumours / knowledge, to gain an advantage etc., through knowing the hidden vulns and reses
* Actually testing things out for hidden vulns and reses isn't particularly fun - rotating through mobs/weapons for all the relevant damage types etc.
* Suddenly finding out that you have a vulnerability because you're taking ~2x damage isn't particularly fun

If we were only talking about hidden resistances, I think actually it would be less compelling to make them visible - occasionally people would be pleasantly surprised, and could benefit even more if they're willing to put all the work in. But with vulns in the mix too, ouch.

**Comment by anhegofcherek** [comment]
> Add strong hints around the items such that players would know that the item has some resistance or vulnerability. (As is, it simply doesn't make sense to test every single item in the game.)

I'd love to see / have seen that generally, but with roughly 100-200 such items, that's...quite a task!

**Comment by anhegofcherek** [comment]
This is now live, enjoy :)
